steps:
  # Install dependencies dan build React app
  - name: node:20
    entrypoint: npm
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    id: 'npm-install'

  - name: node:20
    entrypoint: npm
    args: ['run', 'build']
    id: 'npm-build'

  # Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy --quiet
    timeout: 1600s
    id: 'deploy'

options:
  logging: CLOUD_LOGGING_ONLY


timeout: 1600s